name: Trading Bot

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script
        run: python script.py

      - name: Guardar resultado
        uses: actions/upload-artifact@v3
        with:
          name: ranking
          path: ranking.csv
